#!/usr/bin/env python3

import os
import sys
from os import path
from datetime import datetime


links = {
    'alacritty.yml': '~/.config/alacritty/alacritty.yml',
    'gitconfig': '~/.gitconfig',
    'zshrc': '~/.zshrc',
}

linux_links = {
    'settings.linux.json': '~/.config/Code - OSS/User/settings.json'
}


def main():
    for src, dest in links.items():
        symlink(src, dest)

    if sys.platform == 'linux':
        for src, dest in linux_links.items():
            symlink(src, dest)


def symlink(src, dest):
    # Resolve the full path to the source file
    src = path.abspath(src)
    # Resolve tilda (~) to the user's home directory
    dest = path.expanduser(dest)
    if path.islink(dest):
        print(f'Unlinking {dest}')
        os.remove(dest)
    if path.exists(dest):
        backup(dest)
    print(f'Symlinking {src} -> {dest}')
    os.symlink(src, dest)


def backup(path):
    backup_name = f'{path}.backup-{datetime.now().strftime("%Y-%M-%d-%H-%M-%S")}'
    print(f'Backing up {path} -> {backup_name}')
    os.rename(path, backup_name)


if __name__ == '__main__':
    main()

