"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
console_title_template = "{{ .Shell }} in {{ .Folder }}"
final_space = true
version = 2

[palette]
black = "#1d2021"
blue = "#458588"
aqua = "#689d6a"
orange = "#d65d0e"
red = "#cc241d"
white = "#fbf1c7"
yellow = "#d79921"

[[blocks]]
alignment = "left"
type = "prompt"

  [[blocks.segments]]
  background = "p:yellow"
  foreground = "p:black"
  leading_diamond = ""
  style = "diamond"
  template = " {{ if .SSHSession }} {{ end }}{{ .UserName }} "
  trailing_diamond = ""
  type = "session"

    [blocks.segments.properties]
    display_host = false

  [[blocks.segments]]
  background = "p:orange"
  foreground = "p:white"
  powerline_symbol = ""
  style = "powerline"
  template = "  {{ path .Path .Location }} "
  type = "path"

    [blocks.segments.properties]
    home_icon = "~"
    style = "folder"

  [[blocks.segments]]
  background = "p:aqua"
  background_templates = [
  "{{ if or (.Working.Changed) (.Staging.Changed) }}p:yellow{{ end }}",
  "{{ if and (gt .Ahead 0) (gt .Behind 0) }}p:red{{ end }}",
  "{{ if gt .Ahead 0 }}#49416D{{ end }}",
  "{{ if gt .Behind 0 }}#7A306C{{ end }}"
]
  foreground = "p:black"
  foreground_templates = [
  "{{ if or (.Working.Changed) (.Staging.Changed) }}p:black{{ end }}",
  "{{ if and (gt .Ahead 0) (gt .Behind 0) }}p:white{{ end }}",
  "{{ if gt .Ahead 0 }}p:white{{ end }}"
]
  powerline_symbol = ""
  style = "powerline"
  template = " {{ if .UpstreamURL }}{{ url .UpstreamIcon .UpstreamURL }} {{ end }}{{ .HEAD }}{{ .BranchStatus }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }} "
  type = "git"

    [blocks.segments.properties]
    branch_max_length = 25
    fetch_status = true
    fetch_upstream_icon = true
    github_icon = ""

  [[blocks.segments]]
  background = "p:yellow"
  foreground = "p:white"
  powerline_symbol = ""
  style = "powerline"
  template = "  "
  type = "root"

    [blocks.segments.properties]
    root_icon = ""

  [[blocks.segments]]
  background = "p:blue"
  background_templates = [ "{{ if gt .Code 0 }}p:red{{ end }}" ]
  foreground = "p:white"
  leading_diamond = "<transparent,background></>"
  style = "diamond"
  template = " {{ if gt .Code 0 }}{{ else }}{{ end }} "
  trailing_diamond = ""
  type = "exit"

    [blocks.segments.properties]
    always_enabled = true

[[blocks]]
type = "rprompt"

  [[blocks.segments]]
  background = "transparent"
  foreground = "p:aqua"
  style = "plain"
  template = " "
  type = "node"

    [blocks.segments.properties]
    display_mode = "files"
    fetch_package_manager = false
    home_enabled = false

  [[blocks.segments]]
  background = "transparent"
  foreground = "p:blue"
  style = "powerline"
  template = "ﳑ "
  type = "go"

    [blocks.segments.properties]
    fetch_version = false

  [[blocks.segments]]
  background = "transparent"
  foreground = "p:yellow"
  style = "plain"
  template = " "
  type = "python"

    [blocks.segments.properties]
    display_mode = "files"
    fetch_version = true
    fetch_virtual_env = false

  [[blocks.segments]]
  background = "transparent"
  foreground = "p:white"
  style = "plain"
  template = "in <p:blue><b>{{ .Name }}</b></> "
  type = "shell"

  [[blocks.segments]]
  background = "transparent"
  foreground = "p:white"
  style = "plain"
  template = 'at <p:blue><b>{{ .CurrentDate | date "15:04:05" }}</b></>'
  type = "time"

[secondary_prompt]
background = "transparent"
foreground = "p:black"
template = "<p:yellow,transparent></><,p:yellow> > </><p:yellow,transparent></> "

[[tooltips]]
background = "p:orange"
foreground = "p:white"
leading_diamond = ""
style = "diamond"
template = "  {{ .Profile }}{{ if .Region }}@{{ .Region }}{{ end }} "
tips = [ "aws" ]
trailing_diamond = ""
type = "aws"

  [tooltips.properties]
  display_default = true

[[tooltips]]
background = "p:blue"
foreground = "p:white"
leading_diamond = ""
style = "diamond"
template = " ﴃ {{ .Name }} "
tips = [ "az" ]
trailing_diamond = ""
type = "az"

[transient_prompt]
background = "transparent"
foreground = "p:black"
template = "<p:yellow,transparent></><,p:yellow> {{ .Folder }} </><p:yellow,transparent></> "

