require('user.options')
require('user.keymap')
require('user.plugins')

require('user.airline')
require('user.alpha')
require('user.bufferline')
require('user.colorscheme')
require('user.cmp')
require('user.comment')
require('user.gitsigns')
require('user.impatient')
require('user.indentline')
-- require('user.lualine')
require('user.nvim-tree')
require('user.project')
require('user.toggleterm')
require('user.telescope')
require('user.treesitter')
require('user.lsp')

