require "user.keymap"
require "user.options"
require "user.plugins"

require "user.airline"
require "user.alpha"
require "user.autocommands"
require "user.autopairs"
require "user.bufferline"
require "user.cmp"
require "user.colorscheme"
require "user.comment"
require "user.dap"
require "user.gitsigns"
require "user.illuminate"
require "user.impatient"
require "user.indentline"
require "user.lsp"
-- require "user.lualine"
require "user.nvim-tree"
require "user.project"
require "user.telescope"
require "user.toggleterm"
require "user.treesitter"

